"""init tables

Revision ID: 08b9e8653468
Revises: 
Create Date: 2025-08-11 21:09:13.894479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08b9e8653468'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('squat_type', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('report_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_summaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('avg_score', sa.Float(), nullable=False),
    sa.Column('squat_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_summaries', schema=None) as batch_op:
        batch_op.create_index('idx_username_created_desc', ['username', sa.literal_column('created_at DESC')], unique=False)
        batch_op.create_index(batch_op.f('ix_user_summaries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_summaries_username'), ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_summaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_summaries_username'))
        batch_op.drop_index(batch_op.f('ix_user_summaries_created_at'))
        batch_op.drop_index('idx_username_created_desc')

    op.drop_table('user_summaries')
    op.drop_table('analysis_history')
    # ### end Alembic commands ###
